apiVersion: v1
kind: Service
metadata:
  name: dhvani
  labels:
    app: dhvani
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30037
    targetPort: 80
    protocol: TCP
  selector:
    app: dhvani
